flask-app/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Game(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    score = db.Column(db.Numeric(10))
    time_control = db.Column(db.Numeric(10))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))


class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    games = db.relationship('Game')

flask-app/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from os import path
from flask_login import LoginManager
import os
from dotenv import load_dotenv
load_dotenv()


db = SQLAlchemy()
DB_NAME = "database.db"
database_uri = os.getenv("DATABASE_URI")



def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'
    app.config['SQLALCHEMY_DATABASE_URI'] = database_uri
    db.init_app(app)
    
    migrate = Migrate(app, db)

   

    from .views import views
    from .auth import auth
    from .lingo import lingo

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(lingo, url_prefix='/')

    from .models import Users, Game
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return Users.query.get(int(id))

    return app




def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

flask-app/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Users
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/', methods=['GET', 'POST'])
def welcome():
    return render_template("welcome.html", user=current_user)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = Users.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = Users.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = Users(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='pbkdf2'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

flask-app/website/views.py
from flask import Blueprint, render_template, jsonify, request
from flask_login import login_required, current_user
from . import db
from .models import Game

views = Blueprint('views', __name__)

@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)


@views.route('/adventure')
@login_required
def adventure():
    return render_template("adventure.html", user=current_user)

@views.route('/credits')
def credits():
    return render_template("credits.html", user=current_user)

@views.route('/feedback')
def feedback():
    return render_template("feedback.html", user=current_user)

@views.route('/donate')
def donate():
    return render_template("donate.html", user=current_user)

flask-app/website/templates/adventure.html
{% extends "base.html" %}
{% block title %}adventure{% endblock %}

{% block stylesheet %} 

<link rel="stylesheet" href="{{ url_for('static', filename='css/adventure.css') }}">

{% endblock %}

{% block content%}

<div id="game">
    <div id="stats">
      <span class="stat">XP: <strong><span id="xpText">0</span></strong></span>
      <span class="stat">Health: <strong><span id="healthText">100</span></strong></span>
      <span class="stat">Gold: <strong><span id="goldText">50</span></strong></span>
    </div>
    <div id="controls">
      <button id="button1">Go to store</button>
      <button id="button2">Go to cave</button>
      <button id="button3">Fight dragon</button>
    </div>
    <div id="monsterStats">
      <span class="stat">Monster Name: <strong><span id="monsterName"></span></strong></span>
      <span class="stat">Health: <strong><span id="monsterHealth"></span></strong></span>
    </div>
    <div id="text">Welcome to Dragon Repeller. You must defeat the dragon that is preventing people from leaving the town. You are in the town square. Where do you want to go? Use the buttons above.</div>
</div>

{% endblock %}

flask-app/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
      />

    {% block stylesheet %}
      
    {% endblock %}

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/home">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="welcome" href="/">Home</a>
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

  </body>
</html>

flask-app/website/templates/credits.html
{% extends "base.html" %}
{% block title %}credits{% endblock %}
{% block content%}
{% endblock %}

flask-app/website/templates/donate.html
{% extends "base.html" %}
{% block title %}donate{% endblock %}
{% block content%}
{% endblock %}

flask-app/website/templates/feedback.html
{% extends "base.html" %}
{% block title %}feedback{% endblock %}
{% block content%}
{% endblock %}

flask-app/website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block stylesheet %} 

<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

{% endblock %}

{% block content%}

<ul class="link-list">
    <li><a href="{{ url_for('lingo.game') }}">LINGO</a></li>
    <li><a href="{{ url_for('views.adventure') }}">ADVENTURE</a></li>
    <li><a href="{{ url_for('views.credits') }}">CREDITS</a></li>
    <li><a href="{{ url_for('views.feedback') }}">FEEDBACK</a></li>
    <li><a href="{{ url_for('views.donate') }}">DONATE</a></li>
</ul>

{% endblock %}

flask-app/website/templates/lingo.html
{% extends "base.html" %}

{% block stylesheet %} 

<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/gameContainer.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/scoreContainer.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/leaderboard.css') }}">

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

{% endblock %}

{% block title %}Lingo{% endblock %}
{% block content%}
<div class="lingo">
    <div class="container">

    <div id="game-container">
        <div id="random_value"></div>
        <div id="answer-buttons">
            <button class="answer-btn", id="random_key" disabled></button>
            <button class="answer-btn", id="incorrect_key_one" disabled></button>
            <button class="answer-btn", id="incorrect_key_two" disabled></button>
        </div>
    </div>
    <div class="display-container" id="score-container">
        <div class="title">Score:</div>
        <div class="display" id="score">0</div>
        <button class="executeButton" id="startButton">START</button>
    </div>
    <div class="display-container" id="timer-container">
        <div class="title">Timer:</div>
        <div class="display" id="timer">30</div>
        <button class="executeButton" id="timerFirstButton">0:30</button>
        <button class="executeButton" id="timerSecondButton">1:00</button>
    </div>

    </div>

    <div class="leaderboard-wrapper">
        <div class="display-leaderboard" id="leaderboard-30">
            <h3>Top 10: (30s)</h3>
            <ul id="leaderboard-list-30">
                <!-- Leaderboard entries will be populated here -->
            </ul>
        </div>
        <div class="display-leaderboard" id="leaderboard-60">
            <h3>Top 10: (60s)</h3>
            <ul id="leaderboard-list-60">
                <!-- Leaderboard entries will be populated here -->
            </ul>
        </div>
    </div>
</div>

<script  src="{{ url_for('static', filename='/js/game.js') }}" ></script>

{% endblock %}

flask-app/website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content%}

<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
  </form>

{% endblock %}

flask-app/website/templates/logout.html
{% extends "base.html" %}
{% block title %}Logout{% endblock %}
{% block content%}
{% endblock %}

flask-app/website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign up{% endblock %}
{% block content%}

<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="firstName">First Name</label>
      <input
        type="text"
        class="form-control"
        id="firstName"
        name="firstName"
        placeholder="Enter first name"
      />
    </div>
    <div class="form-group">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1"
        placeholder="Enter password"
      />
    </div>
    <div class="form-group">
      <label for="password2">Password (Confirm)</label>
      <input
        type="password"
        class="form-control"
        id="password2"
        name="password2"
        placeholder="Confirm password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

flask-app/website/templates/welcome.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block stylesheet %} 

<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

{% endblock %}

{% block content%}

<ul class="link-list">
    <li><a href="{{ url_for('auth.login') }}">LINGO</a></li>
    <li><a href="{{ url_for('auth.login') }}">ADVENTURE</a></li>
    <li><a href="{{ url_for('views.credits') }}">CREDITS</a></li>
    <li><a href="{{ url_for('views.feedback') }}">FEEDBACK</a></li>
    <li><a href="{{ url_for('views.donate') }}">DONATE</a></li>
</ul>

{% endblock %}